name: OpenWrt-CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 0'

jobs:
  check_update:
    name: Check Update
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.check_update.outputs.current }}
      latest: ${{ steps.check_update.outputs.latest }}
      release_tag: ${{ steps.check_update.outputs.release_tag }}
    steps:
      - name: Check
        id: check_update
        run: |
          export current=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" | jq -r '.body' | sed -n '2{s/.*\.\.\.//;p}' | tr -d '\r\n')
          echo "current=$current" | tee -a $GITHUB_OUTPUT
          echo "latest=$(curl -s 'https://api.github.com/repos/immortalwrt/immortalwrt/commits/master' | jq -r '.sha' | cut -c1-7)" | tee -a $GITHUB_OUTPUT
          echo "release_tag=$(curl -s 'https://api.github.com/repos/immortalwrt/immortalwrt/tags' | jq -r '.[0].name')" | tee -a $GITHUB_OUTPUT

  build_toolchain:
    name: Build Toolchain and Kernel
    runs-on: ubuntu-24.04
    needs: check_update
    if: needs.check_update.outputs.current != needs.check_update.outputs.latest || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout CI repository
        uses: actions/checkout@v4
        with:
          path: CI

      - name: Setup build environment
        uses: ./CI/.github/actions/setup-build-environment
        with:
          release_tag: ${{ needs.check_update.outputs.release_tag }}
          cache_key: toolchain-kernel

      - name: Compile toolchain and kernel
        id: compile_toolchain
        run: |
          alias mkdir='mkdir -p'
          make tools/compile toolchain/compile target/compile -j$(nproc) || echo "result=fail" >> $GITHUB_OUTPUT

      - name: Compile toolchain and kernel(2)
        id: compile_toolchain2
        if: steps.compile_toolchain.outputs.result == 'fail'
        run: |
          make tools/compile toolchain/compile target/compile V=s -j1 || echo "result=fail" >> $GITHUB_OUTPUT

      - name: Compile toolchain and kernel(3)
        if: steps.compile_toolchain2.outputs.result == 'fail'
        run: |
          make tools/compile toolchain/compile target/compile V=s -j1

      - name: Save cache
        uses: ./CI/.github/actions/save-cache
        with:
          cache_key: toolchain-kernel
          max_size_gb: '9'

  build_openwrt:
    name: Build OpenWrt Firmware
    runs-on: ubuntu-24.04
    needs: [check_update, build_toolchain]
    if: needs.check_update.outputs.current != needs.check_update.outputs.latest || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout CI repository
        uses: actions/checkout@v4
        with:
          path: CI

      - name: Setup build environment
        uses: ./CI/.github/actions/setup-build-environment
        with:
          release_tag: ${{ needs.check_update.outputs.release_tag }}
          cache_key: toolchain-kernel

      - name: Compile OpenWrt
        id: compile1
        run: |
          alias mkdir='mkdir -p'
          make -j$(nproc) || echo "result=fail" >> $GITHUB_OUTPUT

      - name: Compile OpenWrt(2)
        id: compile2
        if: steps.compile1.outputs.result == 'fail'
        run: |
          make V=s -j1 || echo "result=fail" >> $GITHUB_OUTPUT

      - name: Compile OpenWrt(3)
        if: steps.compile2.outputs.result == 'fail'
        run: |
          make V=s -j1

      - name: Clean up
        run: |
          ls bin/targets/x86/64
          df -h

      - name: Save cache
        uses: ./CI/.github/actions/save-cache
        with:
          cache_key: toolchain-kernel
          max_size_gb: '9'

      - name: Upload buildinfo
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_buildinfo
          path: ./bin/targets/x86/64/*.buildinfo

      - name: Upload ext4 images
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_ext4_images
          path: |
            ./bin/targets/x86/64/immortalwrt-x86-64-generic-ext4-combined-efi.*

      - name: Upload squashfs images
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_squashfs_images
          path: |
            ./bin/targets/x86/64/immortalwrt-x86-64-generic-squashfs-combined-efi.*

      - name: Upload rootfs
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_rootfs
          path: ./bin/targets/x86/64/immortalwrt-x86-64-generic-rootfs.tar.gz

      - name: Prepare release
        run: |
          mkdir -p release
          cat > release/fw.json <<EOF
          {
            "x86_64": [
              {
                "build_date": "$(./scripts/get_source_date_epoch.sh)",
                "sha256sum": "$(sha256sum bin/targets/x86/64/immortalwrt-x86-64-generic-squashfs-combined-efi.img.gz | awk '{print $1}')",
                "url": "https://github.com/$GITHUB_REPOSITORY/releases/download/${{ needs.check_update.outputs.release_tag }}/immortalwrt-x86-64-generic-squashfs-combined-efi.img.gz"
              }
            ]
          }
          EOF
          cat release/fw.json
          echo "**Update Time**: $(date -d @$(./scripts/get_source_date_epoch.sh) -Iseconds)" > changelog.md
          echo "**Full Changelog**: https://github.com/immortalwrt/immortalwrt/compare/${{ needs.check_update.outputs.current }}...$(git rev-parse --short HEAD)" >> changelog.md
          cat changelog.md
          mv ./bin/targets/x86/64/immortalwrt-x86-64-generic-ext4-combined-efi.* release/
          mv ./bin/targets/x86/64/immortalwrt-x86-64-generic-squashfs-combined-efi.* release/
          mv ./bin/targets/x86/64/immortalwrt-x86-64-generic-rootfs.tar.gz release/

      - name: Release
        uses: ncipollo/release-action@v1
        if: github.ref_name == 'main' && github.event_name != 'pull_request'
        with:
          allowUpdates: true
          bodyFile: "changelog.md"
          removeArtifacts: true
          tag: ${{ needs.check_update.outputs.release_tag }}
          makeLatest: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "release/*"

      - name: Prepare commit
        run: |
          sed -i \
            -e '/^#\? *CONFIG_BINUTILS_USE_VERSION_/d' \
            -e '/^#\? *CONFIG_GCC_USE_VERSION_/d' \
            -e '/^CONFIG_BINUTILS_VERSION/d' \
            -e '/^CONFIG_GCC_VERSION/d' \
            -e '/^CONFIG_VERSION_/d' \
            .config
          cp .config CI/
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update .config
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          title: Update .config
          body: Update .config
          path: CI
          add-paths: .config
          branch: update-config
