name: Update Config

on:
  schedule:
    - cron: '0 20 * * 0,4'

jobs:
  update_config:
    name: Update Config
    runs-on: ubuntu-24.04
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Checkout OpenWrt
        uses: actions/checkout@v4
        with:
          repository: immortalwrt/immortalwrt

      - name: Update feeds
        run: |
          sed -i '$a src-git smpackage https://github.com/kenzok8/small-package' feeds.conf.default
          ./scripts/feeds update -a
          rm -rf feeds/smpackage/{base-files,dnsmasq,firewall*,fullconenat,libnftnl,nftables,ppp,opkg,ucl,upx,vsftpd*,miniupnpd-iptables,wireless-regdb}
          ./scripts/feeds install -a

      - name: Download configuration file
        uses: actions/checkout@v4
        with:
          path: CI
          
      - name: Configure
        run: |
          cp CI/.config .
          make defconfig
          sed -i \
            -e '/^#\? *CONFIG_BINUTILS_USE_VERSION_/d' \
            -e '/^#\? *CONFIG_GCC_USE_VERSION_/d' \
            -e '/^CONFIG_BINUTILS_VERSION/d' \
            -e '/^CONFIG_GCC_VERSION/d' \
            -e '/^CONFIG_VERSION_/d' \
            .config
          cp .config CI/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update .config
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          title: Update .config
          body: Update .config
          path: CI
          add-paths: .config
          branch: update-config
